apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ugyt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-ugyt@sha256:3e535fa1f202a203402c892557c66fb9bdbcfa27ad3cc9ac4199943d9ec37375
        name: my-nodejs
        resources: {}
status: {}
